apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-db-credentials
  namespace: forgeops-prod
spec:
  encryptedData:
    DB_PASSWORD: AgC4yZ99qK2mP9vL5rT0wV==
    DB_USER: AgD8yW33nL5pQ7vM3rS1tW==
  template:
    metadata:
      name: api-db-credentials
      namespace: forgeops-prod
    type: Opaque
