replicaCount: 2

image:
  repository: ghcr.io/h8rsh100/forgeops-api-service
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
