apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-db-credentials
  namespace: forgeops-dev
spec:
  encryptedData:
    DB_PASSWORD: AgA3xZ87qK1mP9vL5rT0wQ==
    DB_USER: AgB9yW21nL5pQ7vM3rS1tU==
  template:
    metadata:
      name: api-db-credentials
      namespace: forgeops-dev
    type: Opaque
