replicaCount: 1

image:
  repository: ghcr.io/h8rsh100/forgeops-worker-service
  tag: "latest"
  pullPolicy: Always

env:
  pollInterval: "3.0"
  apiServiceUrl: "http://api-service:8000"

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 32Mi
